name: "validation test"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the main branch
        uses: actions/checkout@v4

      - name: checkout the bench_data branch to a given folder
        uses: actions/checkout@v4
        with:
          ref: 'bench_data'
          sparse-checkout: |
            data.json
          sparse-checkout-cone-mode: false
          path: 'bench_data'

      - run: tree

      - name: validate inputs
        uses: ./
        id: validate
        with:
          bench_dir: bench/
          number_of_metrics_to_evaluate: 2
          deploy_instance_meta_public_key: terraform/publickeys/public_key.pub
          deploy_custom_inventory_file_path: terraform/templates/hosts.tpl
          deploy_vars_file_path: terraform/input.tfvars
          deploy_destroy_after_run: true
          snr_extra_file_uploaded_name: updated_all_file
          snr_extra_file_name: all
          snr_extra_file_target_path: ./bench/ansible/group_vars/all
          snr_execution_order: setup,init,run,save_res
          eval_metrics_to_evaluate: request-latency-avg, mb-send-rate
          eval_evaluation_method: trend_detection_deltas
          eval_trend_thresholds: 10, 10
          eval_bucket_result_file_path: results/kafka_2_2_1.json
          eval_comment_to_commit: on
          eval_alert_users_if_bench_failed: '@DawidNiezgodka'

